'use strict';
export const ADD_TODO = 'ADD_TODO';
export const DEL_TODO = 'DEL_TODO';
export const CHANGE_DID_FLAG = 'CHANGE_DID_FLAG';
export const L12NYM_CHG_ADDMEMO = 'L12NYM_CHG_ADDMEMO';
export const L12NYM_EXEC_ADDMEMO = 'L12NYM_EXEC_ADDMEMO';
//export const L12NYM_CHG_FINDMEMO = 'L12NYM_CHG_FINDMEMO';
export const L12NYM_EXEC_FINDMEMO = 'L12NYM_EXEC_FINDMEMO';
export const L12NYM_CHG_DELMEMO = 'L12NYM_CHG_DELMEMO';
export const L12NYM_EXEC_DELMEMO = 'L12NYM_EXEC_DELMEMO';
export const L12NYM_LOAD_ADDRESS = 'L12NYM_LOAD_ADDRESS';


